version: '3.8'
services:
  db:
    image: postgres:15
    container_name: stockalert_db
    environment:
      POSTGRES_DB: stockalert_db
      POSTGRES_USER: stockalert_user
      POSTGRES_PASSWORD: stockalert_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stockalert_user -d stockalert_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: stockalert_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=stockalert_db
      - DB_USER=stockalert_user
      - DB_PASSWORD=stockalert_password
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always

volumes:
  postgres_data:
    driver: local

networks:
  stock-alert-network:
    driver: bridge 